# Generated by Django 5.2.11 on 2026-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_alter_movement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='unit_type',
            field=models.CharField(choices=[('BASE', 'Unidad base'), ('PRESENTATION', 'Presentación')], default='BASE', max_length=20),
        ),
    ]
