# Generated by Django 5.2.11 on 2026-02-20 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0005_alter_movement_edited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movement',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='movement',
            name='unit_name_at_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
