# Generated by Django 5.2.11 on 2026-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0006_movement_cancelled_at_movement_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
