# Generated by Django 5.2.7 on 2026-03-06 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0007_movement_is_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='user_name_at_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
