# Generated by Django 5.2.7 on 2026-03-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_code'),
        ('movements', '0008_movement_user_name_at_time_alter_movement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.product'),
        ),
    ]
