# Generated by Django 5.2.7 on 2026-03-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0009_alter_movement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='resulting_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
