# Generated by Django 5.2.11 on 2026-02-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_has_concentration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='has_presentation_quantity',
            new_name='has_presentation',
        ),
        migrations.AddField(
            model_name='inventory',
            name='has_quantity_per_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='selected_option',
            field=models.IntegerField(choices=[(1, '(Mg, Ml, g, Pastilla) perfecto para medicamentos'), (2, '(Kg, Lb, unidad) perfecto para alimentos'), (3, '(Unidades exactas) perfecto para objetos '), (4, 'Personalizado')], default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='allowed_units',
            field=models.ManyToManyField(blank=True, to='inventory.baseunit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='allowed_presentations',
            field=models.ManyToManyField(blank=True, to='inventory.presentation'),
        ),
    ]
