# Generated by Django 5.2.11 on 2026-02-12 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_baseunit_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.inventory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'inventory')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concentration', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('stock_min', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('base_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.baseunit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.presentation')),
            ],
        ),
    ]
