# Generated by Django 5.2.11 on 2026-02-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
