# Generated by Django 5.2.11 on 2026-02-18 18:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_current_stock_alter_product_stock_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_per_presentation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
    ]
