# Generated by Django 5.2.11 on 2026-02-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_quantity_per_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_min',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_initial_presentations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_min_presentations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
