# Generated by Django 5.2.11 on 2026-02-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_inventories',
            field=models.ManyToManyField(blank=True, related_name='staff', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('maestro', 'Maestro'), ('jefe', 'Jefe'), ('estudiante', 'Estudiante')], default='estudiante', max_length=15),
        ),
    ]
