# Generated by Django 5.2.11 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_assigned_inventories_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Designa si este es un usuario interno del sistema, usado para procesos automáticos.'),
        ),
    ]
